name: Watch External Repo Changes

on:
  schedule:
    # - cron: '*/30 * * * *'  # Runs every 30 minutes
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Manual trigger option

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out monitoring repository
        uses: actions/checkout@v3

      - name: Fetch latest changes from target repository
        run: |
          git remote add target https://github.com/WordPress/gutenberg.git
          git fetch target

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run monitoring script
        env:
          MONITOR_TOKEN: ${{ secrets.MONITOR_TOKEN }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python scripts/monitor_changes.py
